sites/nau/CHANGELOG.md, sites/nau/src/frontend/scss/extras/components/_footer.scss
When we reseted the <a> elements, the footer inherited the default color. This fixes the issue and removes the underline.
=> 💄(footer) fix link hover color

sites/nau/CHANGELOG.md, sites/nau/src/backend/templates/richie/base.html, sites/nau/src/backend/templates/richie/large_banner/hero-intro.html
Fix the search component that is included on header and on the homepage.
The search was redirecting to the /en/course/ page.
That is configured has a DjangoCMS redirect page.
The redirect lost the `query` URL parameter.
The solution is to set the `courses-search` on the /en/courses page.
Then the search component generate URLs directly to the correct page.
Fixes GN-754
=> 🐛(search) fix header and home search component

sites/nau/CHANGELOG.md, sites/nau/src/frontend/scss/extras/components/_header.scss
On header preserve the order of the components:
- language change combo box,
- login button
- register button
So they have the same presentation as the LMS.
@sandroscosta  please review this change.
https://plataforma-nau.atlassian.net/browse/GN-786
=> 💄(header) order of language/login/register

sites/nau/CHANGELOG.md, sites/nau/src/backend/templates/courses/cms/course_detail.html, sites/nau/src/frontend/scss/_extras.scss, sites/nau/src/frontend/scss/extras/components/templates/courses/cms/course_detail.scss
Move enroll button for open to enroll course runs to be higher on the
screen. For a single open course run the enroll button is visible on
the right using a desktop viewport. If using mobile at
least it will be visible for simple swipe instead of scrolling
to the button of the screen.
=> 💄(course_detail) higher enroll button

sites/nau/CHANGELOG.md, sites/nau/src/backend/templates/courses/cms/course_detail.html, sites/nau/src/frontend/scss/extras/components/_subheader.scss
Remove the "In this course you'll learn..." so you can place any text on the "What you'll learn" placeholder.
Replace the red checkmark for a blue one.
Tweak the `_subheader`.
=> 💄(course_detail) remove excessive text in skills

sites/nau/CHANGELOG.md, sites/nau/src/frontend/scss/extras/components/templates/courses/cms/_course_detail.scss
This PR fixes the `.course-plan__title` color, to make it inherit from previous titles on the page. Reverts the color to black.
The organizations title font size was smaller than any other titles after it, so it was fixed to the `h2` size.
#GN-850
=> 💄(course_detail) fix title color and size

sites/nau/CHANGELOG.md, sites/nau/src/backend/nau/settings.py
Lower page content cache from 1 day to 30 minutes
=> 🐛(cache) lower content cache

sites/nau/CHANGELOG.md, sites/nau/src/frontend/scss/extras/components/_subheader.scss
The enroll button was not clickable on small width screen due to an issue with an absolute positioned element on the enrollment details column
Fixed an issue with the styles that generated an issue when activating the enroll button on mobile width screens.
#GN-987
=> Enroll button not clickable on small width screen

sites/nau/CHANGELOG.md, sites/nau/src/backend/nau/cache/cache_ttl.py, sites/nau/src/backend/nau/settings.py, sites/nau/src/backend/nau/tests/test_cache_ttl.py
Limit the cache ttl for course pages based on course run dates.
Issue: openfun/richie#1663
Port PR: openfun/richie#1766
=> 🐛(cache) fix course page cache

Dockerfile, sites/nau/CHANGELOG.md
The nauedu/nau docker image will start to have static assets, to improve rolling deploy of the static assets.
We will stop use the `nauedu/nau-nginx` docker image and use the newer dynamic built nginx image.
This newer nginx image will have the static assets from both current/older and new releases, so the user don't view a missing css during the rolling deploy.
GN-998
GN-1002
=> 👷(docker) add app docker image with static assets

sites/nau/CHANGELOG.md, sites/nau/src/backend/templates/richie/web_analytics.html
Add custom dimensions key/value on custom code for Google Tag Manager. GN-1079
=> 📈(web_analytics) add custom dimensions to GTM

sites/nau/CHANGELOG.md, sites/nau/src/frontend/scss/extras/components/_footer.scss
Increase the size of the white part of footer where some logos are put.
Problem:
The cookie message are overlapping the footer logos.
Changed to:
=> 💄(footer) increase footer white size

sites/nau/CHANGELOG.md, sites/nau/requirements/dev.txt
Upgrade python development dependencies:
- bandit
- pylint
- pylint-django
- pytest
- raincoat
=> ⬆️(nau) upgrade python dev dependencies

sites/nau/CHANGELOG.md, sites/nau/src/backend/nau/settings.py, sites/nau/src/backend/nau/tests/test_maintenance.py, sites/nau/src/backend/nau/tests/test_redirect_course_page.py
After the upgrade of django-cms v3.11.2 we can enable `CMS_REDIRECT_PRESERVE_QUERY_PARAMS` setting that fix the redirect of the parent courses page isn't the same of the course search.
=> 🐛(search) fix redirect for the search course page

sites/nau/CHANGELOG.md, sites/nau/src/backend/templates/djangocms_video/default/video_player.html
Improve course page load time by lazy loading the embed video player. GN-1221
Edit course page screen capture:
View course page screen capture:
It is possible to have a different video poster / thumbnail than the course glimpse image.
You need to add a `poster` image to the Video player component on the Teaser of the course.
=> ⚡️(video) lazy load embed video player

sites/nau/CHANGELOG.md, sites/nau/requirements/base.txt, sites/nau/src/frontend/package.json, sites/nau/src/frontend/yarn.lock
Had to upgrade to 2.24.1 to fix the issue with the grid on the Partner Course list now rendering correctly because it was missing a `<div>` container with a `__content` class.
=> ⬆️(nau) upgrade richie to v2.24.1

sites/nau/CHANGELOG.md, sites/nau/src/backend/templates/djangocms_video/default/video_player.html
On some course images the play of the video player isn't easy visible, removing its opacity.
Changing to:
=> ⚡️(video) style of lazy load embed video player

sites/nau/CHANGELOG.md, sites/nau/requirements/base.txt
A new major version of Django CMS has been released. It introduces heavy breaking changes so, we pin it to version 3 for now. Richie < 2.25 does not pin this dep so until we upgrade to Richie 2.25 we have to pin this dep on rsf side.
Copied from: https://github.com/openfun/fun-richie-site-factory/commit/ec414b3a6a6ab5d28ee2a186bfc090f9f48d9902
=> 📌(backend) pin django-cms to version less than 4

Dockerfile, sites/nau/CHANGELOG.md
Replace s3cmd with awscli, that is more speedy.
relates to fccn/nau-technical#118
=> 👷(s3) replace s3cmd with awscli

sites/nau/CHANGELOG.md, sites/nau/src/backend/locale/en/LC_MESSAGES/django.po, sites/nau/src/backend/locale/pt/LC_MESSAGES/django.po, sites/nau/src/backend/nau/force_translations.py
Override the `blogpost-badges.html` template to remove the unwanted `Richie news`, when sharing via Twitter
Ultimately we can remove the variables but I decided to keep them in, as it makes the code cleaner.
=> 💄(template) override blogpost-badges

.circleci/src/jobs/@docker.yml, .circleci/src/jobs/@frontend.yml, .circleci/src/jobs/@project.yml
Fix the `check-configuration` job, that checks if the existing configuration of Circle CI is the correct one from the templates.
fix #251
=> 💚(CircleCI): fix check-configuration job

Makefile, env.d/development
After the Richie upgrade, with its Django upgrade, etc.
it was no longer possible to run the local backend tests with the
Makefile target `make test-back`.
This fixes it, making the project and its tests to use the `root` MySQL
database user, instead of using the an application user. So when the
tests are starting up, it can create the new test database on the fly.
fixes fccn/nau-richie-site-factory#250
=> 🐛(test) fix run local tests

Dockerfile, sites/nau/CHANGELOG.md, sites/nau/src/backend/nau/urls.py
Remove option of deliver static assets from application docker image, to be more compatible with Richie upstream. Consequence is lower the app docker image size.
The awscli was moved to nginx.
=> ⚡️(assets) static assets only on nginx image

sites/nau/CHANGELOG.md, sites/nau/src/backend/nau/__init__.py, sites/nau/src/frontend/package.json
Fixed
- 🐛(storage) fix missing staticfiles.json after collectstatic
Changed
- ⚡️(assets) static assets only on nginx image. Remove option of deliver static assets from application docker image, to be more compatible with Richie upstream. Consequence is lower the app docker image size. The awscli was moved to nginx.
=> 🔖(nau) bump to version 1.28.0

sites/nau/CHANGELOG.md, sites/nau/src/backend/nau/settings.py
The `STATIC_FILES_URL_ENABLE` setting doesn't do nothing, removing it from the settings.py file.
=> ⚰️(setttings) remove setting

Makefile, sites/nau/CHANGELOG.md, sites/nau/src/backend/base/management/commands/extract_courses_data.py
This PR includes a script to extract courses data as csv format.
Related to #282
=> Create an excel file with all marketing course pages

sites/nau/CHANGELOG.md, sites/nau/src/backend/locale/en/LC_MESSAGES/django.po, sites/nau/src/backend/locale/pt/LC_MESSAGES/django.po, sites/nau/src/backend/nau/settings.py
This PR includes:
- In Portuguese language it was changed from Meus cursos to Painel de Cursos
- Changed menu items positions in accordance with lms
Due to the complexity of validating these changes being included by this PR, particularly regarding running LMS locally, the intention is to deploy to development environment and validate there if the requirements are met. 
This PR is related to:
- Change NAU Richie Menu entry order [#288](https://github.com/fccn/nau-richie-site-factory/issues/288)
- Add order history link to NAU Richie menu [#404](https://github.com/fccn/nau-technical/issues/404)
- Change NAU Richie Menu entry order [#288](https://github.com/fccn/nau-richie-site-factory/issues/288)
=> 💄(menu) adjusted and changed translation of the menu links

sites/nau/CHANGELOG.md, sites/nau/src/backend/templates/courses/cms/blogpost_detail.html, sites/nau/src/frontend/scss/_extras.scss, sites/nau/src/frontend/scss/extras/_reboot.scss, sites/nau/src/frontend/scss/extras/components/_footer.scss, sites/nau/src/frontend/scss/extras/components/_header.scss, sites/nau/src/frontend/scss/extras/components/templates/courses/cms/_blogpost_details.scss, sites/nau/src/frontend/scss/extras/components/templates/courses/cms/_course_detail.scss, sites/nau/src/frontend/scss/extras/components/templates/courses/cms/_organization_detail.scss, sites/nau/src/frontend/scss/extras/components/templates/courses/cms/_program_detail.scss, sites/nau/src/frontend/scss/extras/components/templates/richie/_columns.scss, sites/nau/src/frontend/scss/extras/components/templates/richie/large_banner/_large_banner.scss, sites/nau/src/frontend/scss/extras/settings/_variables.scss, sites/nau/src/frontend/scss/extras/tools/_external_links.scss
- Some font-size and styles were not in accordance with AMA standards. 
- Blogpost template was changed to have only one h1 instead of two.
- Minor tweaks to heading margins for better reading.
- Minor tweaks to footer link padding for 44px minimum height.
https://github.com/fccn/nau-technical/issues/323
=> ♿️(fix) styles and template tweaks

sites/ap/CHANGELOG.md, sites/ap/src/backend/ap/settings.py
🔧(ap) add S3 default ACL setting
Instead of having to change the default S3 bucket policy, just upload
the files with the public-read acl.
fccn/nau-technical#414
---------
🔧(ap) allow to configure  Django Storage from env
Allow to configure the Django `STORAGES` from an environment variable.
This gives the operator more flexibility instead of having to configure
all S3 parameters has environment variables, those can be configured per
storage directly on this new environment variable `DJANGO_STORAGES`.
fccn/nau-technical#414
=> 🔧(ap) add S3 default ACL and allow to configure  Django Storage from env

.circleci/config.yml, env.d/development, sites/nau/CHANGELOG.md, sites/nau/src/backend/nau/settings.py
🔧(nau) add S3 default ACL setting
Instead of having to change the default S3 bucket policy, just upload
the files with the public-read acl.
https://github.com/fccn/nau-technical/issues/414
--------------
🔧(nau) allow to configure Django Storage from env
Allow to configure the Django STORAGES from an environment variable.
This gives the operator more flexibility instead of having to configure
all S3 parameters has environment variables, those can be configured per
storage directly on this new environment variable DJANGO_STORAGES.
https://github.com/fccn/nau-technical/issues/414
=> 🔧(nau) add S3 default ACL and allow to configure Django Storage from env

sites/ap/CHANGELOG.md, sites/ap/src/backend/ap/__init__.py, sites/ap/src/frontend/package.json
Added
- 🔧(ap) add media S3 default ACL to `public-read`
- 🔧(ap) allow to configure Django Storages from environment `DJANGO_STORAGES`
- ✨(ap) added features to meet the first release requirements
- Changed logo image
- Removed english language and leave only portuguese
- Set the missing variable `RICHIE_FILTERS_PRESENTATION` to have the filters working
Changed
- Updated the favicon and apple touch icon variants
=> 🔖(ap) bump to version 1.1.0

.circleci/config.yml, Makefile, sites/ap/src/backend/locale/en/LC_MESSAGES/django.po, sites/ap/src/backend/locale/pt/LC_MESSAGES/django.po, sites/nau/src/backend/locale/en/LC_MESSAGES/django.po, sites/nau/src/backend/locale/pt/LC_MESSAGES/django.po
Remove commented code that prevented the i18n internationalization to be run correctly. Example the NAU site was presenting "Portuguese Lang" on header instead of showing "Português".
=> 🌐(i18n) fix backend i18n

.circleci/config.yml, .gitlint
This commit re-configures the gitlint so it no longer outputs a warning.
WARNING: I1 - ignore-by-title: gitlint will be switching from using Python regex 'match' (match beginning) to 'search' (match anywhere) semantics. Please review your ignore-by-title.regex option accordingly. To remove this warning, set general.regex-style-search=True. More details:
https://jorisroovers.github.io/gitlint/configuration/#regex-style-search
=> 👷(gitlint) fix gitlint warning

.circleci/config.yml, sites/ap/CHANGELOG.md, sites/ap/requirements/base.txt, sites/ap/src/frontend/package.json, sites/ap/src/frontend/yarn.lock
https://github.com/openfun/richie/releases/tag/v3.1.2
Related to [Upgrade NAU Richie #561](https://github.com/fccn/nau-technical/issues/561)
=> ⬆️(ap) upgrade richie to v3.1.2

sites/nau/CHANGELOG.md, sites/nau/requirements/base.txt, sites/nau/src/frontend/package.json, sites/nau/src/frontend/yarn.lock
https://github.com/openfun/richie/releases/tag/v3.1.2
Related to [Upgrade NAU Richie #561](https://github.com/fccn/nau-technical/issues/561)
=> ⬆️(nau) upgrade richie to v3.1.2

sites/ap/CHANGELOG.md, sites/ap/src/backend/ap/__init__.py, sites/ap/src/frontend/package.json
Changed
- 🔥(video) remove lazy load video player
- ⬆️(ap) upgrade dependencies
- 🔧(ap) update settings w/ site cookiecutter
- ⚰️(maintenance) remove maintenance functionality
- ⬆️(ap) upgrade richie to v3.1.2
Fixed
- 🐛(ap) added homepage logo link to the header
=> 🔖(ap) bump to version 1.3.0
