sites/nau/CHANGELOG.md
sites/nau/src/frontend/yarn.lock

Run a `yarn upgrade` so all js dependencies could be upgraded.

⬆️(upgrade) upgrade frontend js libraries

---

sites/nau/CHANGELOG.md
sites/nau/src/frontend/scss/_extras.scss
sites/nau/src/frontend/scss/extras/_reboot.scss
sites/nau/src/frontend/scss/extras/components/_header.scss

Create a reboot.scss file
Add the correct color to regular links;
Correct the selected menu item to have a bottom border;
#GN-725

💄(reboot) default link color

---

sites/nau/CHANGELOG.md
sites/nau/src/frontend/scss/_extras.scss
sites/nau/src/frontend/scss/extras/objects/_category_glimpses.scss
sites/nau/src/frontend/scss/settings/_colors.scss

Fix category-glimpse-list to have the proper width;
Add default colors to the category badges;

💄 Fix category glimpse and badge issues

---

sites/nau/CHANGELOG.md
sites/nau/src/frontend/scss/_extras.scss
sites/nau/src/frontend/scss/extras/components/_search_input.scss
sites/nau/src/frontend/scss/extras/components/_subheader.scss
sites/nau/src/frontend/scss/settings/_colors.scss

Created visual distinction between default search and the NAU theme
Added a new background color

💄(search-input) search bar improvements

---

sites/nau/CHANGELOG.md
sites/nau/requirements/base.txt
sites/nau/src/frontend/package.json
sites/nau/src/frontend/yarn.lock

https://github.com/openfun/richie/releases/tag/v2.11.0
https://github.com/openfun/richie/releases/tag/v2.10.0

⬆️(nau) upgrade richie to v2.11.0

---

sites/nau/src/backend/nau/settings.py

Fix missing facebbok pixel django setting.

🐛(tracking) fix missing facebook pixel setting

---

sites/nau/CHANGELOG.md
sites/nau/src/backend/nau/tests/test_error_view.py
sites/nau/src/backend/templates/richie/error.html

If page not found exists on arquivo.pt, then add a link to view it on arquivo.pt

✨(404) add arquivo404 js to 404 page on Richie

---

sites/nau/CHANGELOG.md
sites/nau/src/backend/locale/en/LC_MESSAGES/django.po
sites/nau/src/backend/locale/pt/LC_MESSAGES/django.po

Collect and translate .po files. GN-768

🌐(i18n) translate missing string

---

sites/nau/CHANGELOG.md
sites/nau/requirements/base.txt
sites/nau/src/frontend/package.json
sites/nau/src/frontend/yarn.lock

https://github.com/openfun/richie/releases/tag/v2.12.0

⬆️(nau) upgrade richie to v2.12.0

---

sites/nau/CHANGELOG.md
sites/nau/src/frontend/package.json
sites/nau/src/frontend/yarn.lock

Upgrade frontend dependencies

---

sites/nau/CHANGELOG.md
sites/nau/src/frontend/scss/_extras.scss
sites/nau/src/frontend/scss/extras/components/_course_glimpses.scss
sites/nau/src/frontend/scss/extras/settings/colors/_theme.scss

Rework of the course glimpse cards to display only the needed info.
SVGs and footer information were removed through CSS rules.

Course-glimpse card rework

---

sites/nau/CHANGELOG.md
sites/nau/src/backend/locale/en/LC_MESSAGES/django.po
sites/nau/src/backend/locale/pt/LC_MESSAGES/django.po
sites/nau/src/backend/nau/force_translations.py

Change translations of 'Persons' and 'First session' for PT and EN.

🌐(i18n) change translation

---

sites/nau/CHANGELOG.md
sites/nau/src/frontend/scss/_extras.scss
sites/nau/src/frontend/scss/extras/components/templates/courses/cms/_blogpost_details.scss
sites/nau/src/frontend/scss/extras/components/templates/richie/large_banner/_large_banner.scss
sites/nau/src/frontend/scss/extras/objects/_blogpost_glimpses.scss

Fix the issue where the color of the text on the blog post category tag was displayed incorrectly.
#GN-788

🐛(css) fix blog category tags text color

---

docker-compose.yml
env.d/development
sites/nau/CHANGELOG.md

Upgrade elastic search to version 7.17.0

⬆️(search) upgrade elastic search to 7.17.0

---

sites/nau/CHANGELOG.md
sites/nau/requirements/base.txt
sites/nau/src/backend/nau/settings.py
sites/nau/src/frontend/package.json
sites/nau/src/frontend/yarn.lock

https://github.com/openfun/richie/releases/tag/v2.13.0

⬆️(nau) upgrade richie to v2.13.0

---

sites/nau/CHANGELOG.md
sites/nau/src/frontend/scss/extras/components/templates/courses/cms/course_detail.scss

fix check mark color when course skills contains a list of items on
course page

💄(css) fix check mark color

---

.circleci/config.yml
.circleci/src/jobs/@project.yml
sites/nau/CHANGELOG.md

Fix circleci check configuration step
GN-853

💚(circleci) fix circleci check configuration step

---

sites/nau/CHANGELOG.md
sites/nau/src/backend/locale/en/LC_MESSAGES/django.po
sites/nau/src/backend/locale/pt/LC_MESSAGES/django.po

Fix missing translations like 'Other course runs' GN-849

🌐(i18n) missing translations

---

sites/nau/CHANGELOG.md
sites/nau/requirements/base.txt
sites/nau/requirements/dev.txt

⬆️(dependencies) upgrade python dependencies

---

.github/dependabot.yml

Add specific dependabot configuration for backend and frontend

💚(dependabot) add dependabot config

---

sites/nau/CHANGELOG.md
sites/nau/requirements/base.txt
sites/nau/src/frontend/package.json
sites/nau/src/frontend/yarn.lock

https://github.com/openfun/richie/releases/tag/v2.14.1

⬆️(nau) upgrade richie to v2.14.1

---

sites/nau/CHANGELOG.md
sites/nau/src/backend/nau/chatbot/context_processors.py
sites/nau/src/backend/nau/tests/test_chatbot.py
sites/nau/src/backend/templates/nau/chatbot.html

Add the course parameter to chatbot widget
GN-860

✨(chatbot) add course parameter

---

Dockerfile
docker/files/usr/local/etc/gunicorn/app.py

Fix comment on docker file and on gunicorn startup script.

📝(doc) fix comments

---

env.d/development
sites/nau/CHANGELOG.md
sites/nau/src/backend/nau/google_tag_manager/context_processors.py
sites/nau/src/backend/nau/settings.py
sites/nau/src/backend/nau/tests/test_google_tag_manager.py
sites/nau/src/backend/templates/richie/base.html
sites/nau/src/backend/templates/richie/web_analytics.html

Add Google Tag Manager to nau site without using Richie upstream Web
Analytics.

✨(googletagmanager) add Google Tag Manager

---

sites/cacademy/CHANGELOG.md
sites/cacademy/src/backend/cacademy/settings.py
sites/cacademy/src/backend/cacademy/urls.py
sites/nau/CHANGELOG.md
sites/nau/src/backend/nau/settings.py
sites/nau/src/backend/nau/urls.py

Add a setting that can be enabled to make django deliver static assets.

🔧(rolling_deploy) add setting to deliver static

---

sites/nau/CHANGELOG.md
sites/nau/src/frontend/scss/_extras.scss
sites/nau/src/frontend/scss/extras/components/_subheader.scss
sites/nau/src/frontend/scss/extras/components/templates/courses/cms/_person_detail.scss
sites/nau/src/frontend/scss/extras/objects/_blogpost_glimpses.scss
sites/nau/src/frontend/scss/extras/objects/_category_glimpses.scss

This pull request is an aggregate of multiple CSS fixes

Layout fixes - Backlog

---

.circleci/config.yml
sites/nau/CHANGELOG.md
sites/nau/requirements/base.txt

Add pip requests package for open edx lms backend.
Related to openfun/richie#1768

➕(dependencies) add requests package

---

.circleci/config.yml
.circleci/src/jobs/@backend.yml

Remove the raincoat back lint because it won't run on circleci.

👷(raincoat) remove raincoat

---

.circleci/config.yml
sites/nau/CHANGELOG.md
sites/nau/src/frontend/scss/_extras.scss
sites/nau/src/frontend/scss/extras/objects/_category_glimpses.scss
sites/nau/src/frontend/scss/extras/objects/_course_glimpses.scss

Background clean up on Icon tags for course cards.
https://plataforma-nau.atlassian.net/browse/GN-967
#GN-967

🐛(scss) fix issues with background on icon tag

---

sites/nau/CHANGELOG.md
sites/nau/src/backend/locale/en/LC_MESSAGES/django.po
sites/nau/src/backend/locale/pt/LC_MESSAGES/django.po
sites/nau/src/backend/nau/help_desk/context_processors.py
sites/nau/src/backend/nau/settings.py
sites/nau/src/backend/nau/tests/test_help_desk.py
sites/nau/src/backend/templates/richie/base.html
sites/nau/src/frontend/scss/_extras.scss
sites/nau/src/frontend/scss/extras/components/_header.scss
sites/nau/src/frontend/scss/extras/components/templates/courses/cms/_category_detail.scss

Remove category tag icon

---

sites/nau/CHANGELOG.md
sites/nau/src/backend/nau/settings.py
sites/nau/src/backend/nau/tests/test_language_cookies.py

Add django language settings that allows to
configure language cookies differently,
so we can share it with the open edx.

🔧(language) add django language settings

---

sites/nau/CHANGELOG.md
sites/nau/src/backend/locale/en/LC_MESSAGES/django.po
sites/nau/src/backend/locale/pt/LC_MESSAGES/django.po
sites/nau/src/backend/nau/force_translations.py

Share course on email reference Richie instead of NAU

🌐(i18n) fix share course mailto

---

sites/nau/CHANGELOG.md
sites/nau/requirements/base.txt
sites/nau/src/frontend/package.json
sites/nau/src/frontend/yarn.lock

https://github.com/openfun/richie/releases/tag/v2.16.0

⬆️(nau) upgrade richie to v2.16.0

---

Dockerfile
sites/nau/CHANGELOG.md

Upgrade nginx to latest stable release 1.22.1

⬆️(nginx) upgrade nginx

---

sites/nau/CHANGELOG.md
sites/nau/src/backend/nau/cookie_bar/context_processors.py
sites/nau/src/backend/nau/facebook_pixel/context_processors.py
sites/nau/src/backend/nau/settings.py
sites/nau/src/backend/nau/tests/test_cookie_bar.py
sites/nau/src/backend/templates/nau/cookies.html

Now the cookie bar is optional. To activate it use COOKIE_BAR setting.

✨(cookies) make cookie bar optional

---

gitlint/gitlint_emoji.py
sites/nau/CHANGELOG.md

🐛(gitmoji) fix git lint with emoji

---

sites/nau/CHANGELOG.md
sites/nau/src/backend/nau/google_tag_manager/context_processors.py
sites/nau/src/backend/nau/settings.py
sites/nau/src/backend/nau/tests/test_google_tag_manager.py
sites/nau/src/backend/templates/richie/base.html
sites/nau/src/backend/templates/richie/web_analytics.html

Improve Google Tag Manager JavaScrip tag with custom configuration per environment.
GN-1079

📈(web_analytics) allow deploy GTM per env

---

sites/nau/CHANGELOG.md
sites/nau/src/backend/nau/settings.py

Allow to configure multiple elastic search instances

⬆️(search) config multiple elastic search

---

Makefile
sites/nau/CHANGELOG.md
sites/nau/src/frontend/jest.config.js
sites/nau/src/frontend/js/utils/api/lms/openedx-hawthorn.spec.ts
sites/nau/src/frontend/js/utils/api/lms/openedx-hawthorn.ts
sites/nau/src/frontend/overrides.json
sites/nau/src/frontend/scss/_main.scss
sites/nau/src/frontend/scss/extras/_reboot.scss
sites/nau/src/frontend/scss/extras/colors/_palette.scss
sites/nau/src/frontend/scss/extras/colors/_theme.scss
sites/nau/src/frontend/scss/extras/components/_blogpost_glimpses.scss
sites/nau/src/frontend/scss/extras/components/_content.scss
sites/nau/src/frontend/scss/extras/components/_course_glimpses.scss
sites/nau/src/frontend/scss/extras/components/_header.scss
sites/nau/src/frontend/scss/extras/components/_search_input.scss
sites/nau/src/frontend/scss/extras/components/_subheader.scss
sites/nau/src/frontend/scss/extras/components/templates/courses/cms/_blogpost_details.scss
sites/nau/src/frontend/scss/extras/components/templates/courses/cms/_category_detail.scss
sites/nau/src/frontend/scss/extras/components/templates/courses/cms/_course_detail.scss
sites/nau/src/frontend/scss/extras/components/templates/courses/cms/_person_detail.scss
sites/nau/src/frontend/scss/extras/components/templates/richie/large_banner/_large_banner.scss
sites/nau/src/frontend/scss/extras/objects/_blogpost_glimpses.scss
sites/nau/src/frontend/scss/extras/objects/_category_glimpses.scss
sites/nau/src/frontend/scss/extras/objects/_course_glimpses.scss
sites/nau/src/frontend/scss/extras/settings/_variables.scss

✅ (jest) add jest tests to site factory
:sparkles: (api) update openedx-hawthorn adapter

Add Lilac adapter with custom error payload

---

sites/nau/CHANGELOG.md
sites/nau/requirements/base.txt
sites/nau/src/frontend/package.json
sites/nau/src/frontend/yarn.lock

https://github.com/openfun/richie/releases/tag/v2.18.0 https://github.com/openfun/richie/releases/tag/v2.19.0 https://github.com/openfun/richie/releases/tag/v2.20.0 https://github.com/openfun/richie/releases/tag/v2.20.1

⬆️(nau) upgrade richie to v2.20.1

---

sites/nau/CHANGELOG.md
sites/nau/requirements/base.txt
sites/nau/requirements/dev.txt
sites/nau/src/backend/base/tests/test_views.py
sites/nau/src/backend/nau/settings.py
sites/nau/src/backend/nau/urls.py

Add django-check-seo package to make it more easy to check seo quality.

✨(seo) add django-check-seo

---

sites/nau/CHANGELOG.md
sites/nau/requirements/base.txt
sites/nau/src/frontend/package.json
sites/nau/src/frontend/yarn.lock

Upgrade Richie to version 2.22.0.
Upgrade frontend dependencies.

⬆️(nau) upgrade richie to v2.22.0

---

sites/nau/CHANGELOG.md
sites/nau/src/backend/nau/settings.py

Improve performance by hint browsers to pre-connect to CDN or S3 that has the media files.

⚡️(html) pre-connect to CDN or S3

---

sites/nau/src/backend/locale/en/LC_MESSAGES/django.po
sites/nau/src/backend/locale/pt/LC_MESSAGES/django.po
sites/nau/src/backend/nau/tests/test_courses_templates_course_detail_rendering.py

Add missing test for the lazy load embed video player. 
GN-1221

✅(video) add test for lazy load embed video player

---

.circleci/config.yml
.circleci/src/jobs/@backend.yml
.circleci/src/jobs/@docker.yml
.circleci/src/jobs/@frontend.yml
.circleci/src/jobs/@project.yml
sites/nau/CHANGELOG.md
sites/nau/src/frontend/package.json
sites/nau/src/frontend/yarn.lock

Upgrade the circleci build from Richie cookiecutter, this is a mandatory before upgrading Richie to the next release.

💚(circleci) upgrade circleci build

---

sites/nau/CHANGELOG.md
sites/nau/src/backend/locale/en/LC_MESSAGES/django.po
sites/nau/src/backend/locale/pt/LC_MESSAGES/django.po
sites/nau/src/backend/templates/nau/_footer.html

Improve accessibility in NAU footer logo with a link to homepage.
This change make homepage with 100% accessible on the homepage. At least without cookie banner and without chatbot.

♿️(footer) improve accessibility in footer

---

sites/nau/CHANGELOG.md
sites/nau/src/frontend/scss/extras/components/_course_glimpses.scss

Show the course glimpse footer with a style similar to the organization. 
openfun/richie#2007
Changed from:
Change to:

💄(course_glimpse) show course glimpse footer

---

sites/nau/CHANGELOG.md
sites/nau/src/backend/templates/social-networks/footer-badges.html

We are removing the link to instagram for now.
I decided to put it into a comment, because this will be active soon.
Closes #186

💄(ui) comment out instagram link on the footer

---

sites/nau/CHANGELOG.md
sites/nau/src/frontend/scss/extras/components/_header.scss
sites/nau/src/frontend/scss/extras/components/templates/richie/large_banner/_large_banner.scss

Refactor to create distinct visual.
Work done
#GN-1278

💄(ui) refactor hero section

---

sites/nau/CHANGELOG.md
sites/nau/src/backend/nau/settings.py

feat: additional sentry settings

---

sites/nau/CHANGELOG.md
sites/nau/requirements/base.txt
sites/nau/src/backend/nau/settings.py

Add django_snippet to format HTML content
resolves #196

📌(plugins) add django_snippet

---

sites/nau/src/backend/locale/en/LC_MESSAGES/django.po
sites/nau/src/backend/locale/pt/LC_MESSAGES/django.po

The CI isn't verifying if the i18n translations are synchronized with the code.

🌐(i18n) clean unnecessary translations

---

sites/nau/CHANGELOG.md
sites/nau/src/backend/nau/settings.py

Configure the Dockerflow healthcheck views for
Kubernetes liveness checks.

🩺(kubernetes) liveness checks

---

sites/nau/CHANGELOG.md
sites/nau/src/backend/nau/settings.py
sites/nau/src/backend/nau/urls.py

Add course redirect and joainie urls
From: /redirects/courses/CDIPT/
To: /en/curso/o-digital-e-para-todos/

✨(redirect) add course redirect and joainie urls

---

sites/nau/CHANGELOG.md
sites/nau/src/backend/base/tests/test_redirects.py
sites/nau/src/backend/base/urls.py
sites/nau/src/backend/base/views.py
sites/nau/src/backend/nau/urls.py

Add Open edX redirects to course page
and redirects/partners/<org_code>.
resolves #229

✨(redirect) add new redirects to course and org

---

sites/nau/CHANGELOG.md
sites/nau/src/backend/nau/__init__.py
sites/nau/src/frontend/package.json

Changed
- 💚(circleci) upgrade circleci build
- 👷(docker) upgrade nodejs and python
- ⬆️(nau) upgrade richie to v2.28.0
- 💄(footer) refactor footer logos placeholder
- 💄(header) update nau fccn logo
Fixed
- 🚨(pylint) fix pylint errors on the backend
Added
- ✨(redirect) add new redirects to course and org

🔖(nau) bump to version 1.27.0

---

sites/nau/CHANGELOG.md
sites/nau/src/backend/templates/courses/cms/course_detail.html

Google Search Console requires more information for the RDFa Course information.
fix #197

🐛(rdfa) fix RDFa Course errors

---

sites/nau/CHANGELOG.md
sites/nau/src/backend/locale/en/LC_MESSAGES/django.po
sites/nau/src/backend/locale/pt/LC_MESSAGES/django.po
sites/nau/src/backend/nau/force_translations.py

Remove unnecessary custom translations that already have been pushed upstream on Richie.

🌐(i18n) review exiting force translations

---

.circleci/config.yml
Makefile
docker-compose.yml
sites/ap_nau/CHANGELOG.md
sites/ap_nau/requirements/base.txt
sites/ap_nau/src/backend/ap_nau/__init__.py
sites/ap_nau/src/backend/ap_nau/settings.py
sites/ap_nau/src/frontend/package.json

Added ci build for ap site following the same structure of site nau site.

👷(ap) added ci build for ap site

---

sites/ap/CHANGELOG.md
sites/ap/src/backend/ap/settings.py

Filters defined according to the last update on the requirements.

✨(ap) define search filters

---

.circleci/config.yml
sites/ap/CHANGELOG.md
sites/ap/src/backend/ap/settings.py
sites/ap/src/backend/ap/tests/test_cache_ttl.py
sites/ap/src/backend/ap/tests/test_courses_templates_course_detail_rendering.py
sites/ap/src/backend/ap/tests/test_error_view.py
sites/ap/src/backend/ap/tests/test_google_tag_manager.py
sites/ap/src/backend/ap/tests/test_help_desk.py
sites/ap/src/backend/ap/tests/test_language_cookies.py
sites/ap/src/backend/ap/tests/test_maintenance.py
sites/ap/src/backend/ap/tests/test_open_graph.py
sites/ap/src/backend/ap/tests/test_redirect_course_page.py
sites/ap/src/backend/base/static/richie/images/ap_logo.svg
sites/ap/src/backend/base/tests/test_cache.py
sites/ap/src/backend/base/tests/test_redirects.py
sites/ap/src/backend/base/tests/test_settings.py
sites/ap/src/backend/locale/en/LC_MESSAGES/django.po
sites/ap/src/backend/locale/pt/LC_MESSAGES/django.po

- Changed logo image
- Removed english language and leave only portuguese
- Set the missing variable `RICHIE_FILTERS_PRESENTATION` to have the filters working
Related to [this](https://github.com/fccn/nau-technical/issues/489) card.

✨(ap) added features to meet the first release requirements

---

sites/ap/CHANGELOG.md
sites/ap/src/backend/ap/__init__.py
sites/ap/src/frontend/package.json

Fixed
- 🐛(ap) adjusted login redirect
- Override backend authentication to adjust the login redirect

🔖(ap) bump to version 1.1.1

---

.circleci/config.yml
bin/restore
env.d/development

🔨(mysql) add db restore script 
Add MySQL database restore script.
-----
🔨(mysql) MySQL user from site 
Use dynamic MySQL user from site variable.

🔨(mysql) add db restore script and user from site

---

sites/ap/CHANGELOG.md
sites/ap/requirements/base.txt
sites/ap/src/backend/ap/settings.py
sites/ap/src/frontend/package.json
sites/ap/src/frontend/scss/extras/colors/_theme.scss
sites/ap/src/frontend/scss/extras/components/_course_glimpses.scss
sites/ap/src/frontend/yarn.lock

https://github.com/openfun/richie/releases/tag/v3.0.0

⬆️(ap) upgrade richie to v3.0.0

---

.circleci/config.yml
bin/ci
sites/ap/CHANGELOG.md

- Regenerate the CI configuration file to have the new release image

💚(ap) adjust CI build

---

sites/ap/CHANGELOG.md
sites/ap/src/backend/ap/__init__.py
sites/ap/src/frontend/package.json

🔖(ap) bump to version 1.2.1

---

.circleci/config.yml
sites/nau/CHANGELOG.md
sites/nau/requirements/base.txt
sites/nau/src/backend/nau/settings.py
sites/nau/src/frontend/package.json
sites/nau/src/frontend/scss/extras/colors/_theme.scss
sites/nau/src/frontend/scss/extras/components/_course_glimpses.scss
sites/nau/src/frontend/yarn.lock

https://github.com/openfun/richie/releases/tag/v3.0.0

⬆️(nau) upgrade richie to v3.0.0

---

.circleci/config.yml
sites/ap/CHANGELOG.md
sites/ap/requirements/base.txt
sites/ap/src/backend/locale/en/LC_MESSAGES/django.po
sites/ap/src/backend/locale/pt/LC_MESSAGES/django.po

Upgrade dependencies to be equal to the Richie site cookiecutter

⬆️(ap) upgrade dependencies

---

sites/nau/CHANGELOG.md
sites/nau/src/backend/nau/__init__.py
sites/nau/src/frontend/package.json

Fixed
- 🐛(nau) fix large banner breakpoints
- 🩹(nau) tweak styles on course detail page
- 🩹(nau) tweak styles on program detail page
Changed
- ♻(cunningham) refactor cunningham configuration file

🔖(nau) bump to version 2.1.0

---

sites/nau/CHANGELOG.md
sites/nau/src/frontend/scss/extras/components/_footer.scss

Fix the display of the vertical bar when the img is inside a link

🐛(nau) fix footer logos vertical bar

---

sites/nau/CHANGELOG.md
sites/nau/src/frontend/scss/extras/components/templates/courses/cms/_program_detail.scss

Fix the padding on the program detail page
to avoid out or line elements.
https://github.com/fccn/nau-richie-site-factory/issues/332

🐛(nau) fix program detail padding

---

.circleci/config.yml
sites/ap/CHANGELOG.md
sites/ap/src/backend/ap/settings.py

Update the Django settings with the Richie site cookiecutter.

🔧(ap) update settings w/ site cookiecutter

---

.circleci/config.yml
sites/nau/CHANGELOG.md
sites/nau/src/frontend/scss/extras/components/_subheader.scss
sites/nau/src/frontend/scss/extras/components/templates/courses/cms/_course_detail.scss
sites/nau/src/frontend/scss/extras/components/templates/courses/cms/_organization_detail.scss
sites/nau/src/frontend/scss/extras/components/templates/courses/cms/_program_detail.scss

Fix some issues with side spacing on mobile viewports.

Fix rebranding mobile spacing

---

sites/nau/CHANGELOG.md
sites/nau/requirements/base.txt
sites/nau/src/frontend/package.json
sites/nau/src/frontend/yarn.lock

https://github.com/openfun/richie/releases/tag/v3.1.0
Related to [this](https://github.com/fccn/nau-technical/issues/561) issue.

⬆️(nau) upgrade richie to v3.1.0
